# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crossagent < Formula
  desc "Cross-model AI agent orchestrator with browser-based Web UI"
  homepage "https://github.com/grikwong/crossagent"
  version "1.8.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grikwong/crossagent/releases/download/v1.8.0/crossagent_darwin_amd64.tar.gz"
      sha256 "e112dffd78788ec2420c53b8061bac39fae09409c73c1ab32fcd8d04c8e8a801"

      define_method(:install) do
        bin.install "crossagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grikwong/crossagent/releases/download/v1.8.0/crossagent_darwin_arm64.tar.gz"
      sha256 "3e7fb9fa829307076a6e8dfb1c8ddefdbf91170a236ec7c4921b7caa52a3613b"

      define_method(:install) do
        bin.install "crossagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grikwong/crossagent/releases/download/v1.8.0/crossagent_linux_amd64.tar.gz"
      sha256 "528597b8cadce5930cafe64705709e6a6a156e986162317f038765603fbebb23"
      define_method(:install) do
        bin.install "crossagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grikwong/crossagent/releases/download/v1.8.0/crossagent_linux_arm64.tar.gz"
      sha256 "0c430a8117e35112310bd9b9c5a712c30db7cf28ca9b943595ea7c11b7fae518"
      define_method(:install) do
        bin.install "crossagent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crossagent --version", 2)
  end
end
