# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crossagent < Formula
  desc "Cross-model AI agent orchestrator with browser-based Web UI"
  homepage "https://github.com/grikwong/crossagent"
  version "1.5.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grikwong/crossagent/releases/download/v1.5.0/crossagent_darwin_amd64.tar.gz"
      sha256 "a788a394cc009227e12954ba3d26526a0dde99a6e306c9c391fa890446e0ef98"

      define_method(:install) do
        bin.install "crossagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grikwong/crossagent/releases/download/v1.5.0/crossagent_darwin_arm64.tar.gz"
      sha256 "61b701914d246fe624c3f5b6e20b11de1d25e2d10d184501d5c08294bb33615b"

      define_method(:install) do
        bin.install "crossagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grikwong/crossagent/releases/download/v1.5.0/crossagent_linux_amd64.tar.gz"
      sha256 "acd0261efc4fcb69fef8f8360039e3b0b31065d4456135c4f5bfab213c090ae0"
      define_method(:install) do
        bin.install "crossagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grikwong/crossagent/releases/download/v1.5.0/crossagent_linux_arm64.tar.gz"
      sha256 "e45408d6eb23f4bc4bb8098ac2163364bec9368b8bf1dd4342831bcdded4342a"
      define_method(:install) do
        bin.install "crossagent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crossagent --version", 2)
  end
end
