# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crossagent < Formula
  desc "Cross-model AI agent orchestrator with browser-based Web UI"
  homepage "https://github.com/grikwong/crossagent"
  version "1.3.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grikwong/crossagent/releases/download/v1.3.0/crossagent_darwin_amd64.tar.gz"
      sha256 "e3b79bed0a239a67a82ee320e3950943b4cbb277c532bf6dbba81f7475a3bcf0"

      define_method(:install) do
        bin.install "crossagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grikwong/crossagent/releases/download/v1.3.0/crossagent_darwin_arm64.tar.gz"
      sha256 "a388b25ec342e4714d008ffb36c5540161908444121088c7317a32bd173fbec1"

      define_method(:install) do
        bin.install "crossagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grikwong/crossagent/releases/download/v1.3.0/crossagent_linux_amd64.tar.gz"
      sha256 "6df2599da01d568044da22a39e359d9b173c06745e294e0cf13d91e8b7301abc"
      define_method(:install) do
        bin.install "crossagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grikwong/crossagent/releases/download/v1.3.0/crossagent_linux_arm64.tar.gz"
      sha256 "aad1ca27d8724ff9ef09dbe3d6d4eb28ff9b6c4302ad773c53d155b073dddd3b"
      define_method(:install) do
        bin.install "crossagent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crossagent --version", 2)
  end
end
